version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  app:
    image: lucid-app
    container_name: application
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0"
    ports:
      - "8001:8000"
    environment:
      DB_URL: 'mysql+pymysql://root:root@db:3306/db'


volumes:
  my-db:
